apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: prometheus
  name: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus
          ports:
            - containerPort: 9090
          args:
            - --config.file=/etc/prometheus/prometheus.yml
          volumeMounts:
            - mountPath: /prometheus
              name: prom-data
      restartPolicy: Always
      volumes:
        - name: prom-data
          persistentVolumeClaim:
            claimName: prom-data
